// export const MockUniversities = [
//   {
//     id: 1,
//     name: "Монгол Улсын Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-arts.jpg",
//     status: "open" as const,
//     minScore: "ЭЕШ 500+",
//     admissionRate: "40%",
//     deadline: null,
//     nextCycle: null,
//   },
//   {
//     id: 2,
//     name: "Шинжлэх Ухаан Технологийн Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-business.jpg",
//     status: "closing-soon" as const,
//     minScore: "ЭЕШ 520+",
//     admissionRate: null,
//     deadline: "2024-10-15",
//     nextCycle: null,
//   },
//   {
//     id: 3,
//     name: "Анагаахын Шинжлэх Ухааны Үндэсний Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-medical.jpg",
//     status: "closed" as const,
//     minScore: "ЭЕШ 560+",
//     admissionRate: null,
//     deadline: null,
//     nextCycle: "2025 хавар",
//   },
//   {
//     id: 4,
//     name: "Хүмүүнлэгийн Ухааны Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-tech.jpg",
//     status: "open" as const,
//     minScore: "ЭЕШ 480+",
//     admissionRate: "55%",
//     deadline: null,
//     nextCycle: null,
//   },
//   {
//     id: 5,
//     name: "Санхүү Эдийн Засгийн Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-arts.jpg",
//     status: "closing-soon" as const,
//     minScore: "ЭЕШ 530+",
//     admissionRate: null,
//     deadline: "2024-11-01",
//     nextCycle: null,
//   },
//   {
//     id: 6,
//     name: "Соёл Урлагийн Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-arts.jpg",
//     status: "open" as const,
//     minScore: "Авьяасын шалгалт + ЭЕШ 450+",
//     admissionRate: null,
//     deadline: null,
//     nextCycle: "2025 намар",
//   },
//   {
//     id: 7,
//     name: "Хууль Сахиулахын Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-law.jpg",
//     status: "open" as const,
//     minScore: "ЭЕШ 510+",
//     admissionRate: "35%",
//     deadline: null,
//     nextCycle: null,
//   },
//   {
//     id: 8,
//     name: "Боловсролын Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-education.jpg",
//     status: "open" as const,
//     minScore: "ЭЕШ 470+",
//     admissionRate: "60%",
//     deadline: null,
//     nextCycle: null,
//   },
//   {
//     id: 9,
//     name: "Хөдөө Аж Ахуйн Их Сургууль",
//     location: "Дархан",
//     image: "/university-logo-agriculture.jpg",
//     status: "closing-soon" as const,
//     minScore: "ЭЕШ 460+",
//     admissionRate: null,
//     deadline: "2024-10-25",
//     nextCycle: null,
//   },
//   {
//     id: 10,
//     name: "Мэдээлэл Харилцаа Холбооны Технологийн Их Сургууль",
//     location: "Улаанбаатар",
//     image: "/university-logo-it.jpg",
//     status: "open" as const,
//     minScore: "ЭЕШ 540+",
//     admissionRate: "30%",
//     deadline: null,
//     nextCycle: null,
//   },
// ];